// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGd2oysjiPd6r5no_TsWcrjxE7ZkVmk8M',
    appId: '1:360003452424:web:4d279adc7fc9344aae9bbd',
    messagingSenderId: '360003452424',
    projectId: 'interviewai-eb294',
    authDomain: 'interviewai-eb294.firebaseapp.com',
    storageBucket: 'interviewai-eb294.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_vMHymCDefTGKlDqH-tmx2fzOGR4nRw',
    appId: '1:360003452424:android:0cdc8a2f7433884cae9bbd',
    messagingSenderId: '360003452424',
    projectId: 'interviewai-eb294',
    storageBucket: 'interviewai-eb294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbn-EOAqanwRu_jZGJ9aPJqpLWzx7a4OE',
    appId: '1:360003452424:ios:259874b75d18916eae9bbd',
    messagingSenderId: '360003452424',
    projectId: 'interviewai-eb294',
    storageBucket: 'interviewai-eb294.firebasestorage.app',
    iosBundleId: 'com.interviewai.interviewai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbn-EOAqanwRu_jZGJ9aPJqpLWzx7a4OE',
    appId: '1:360003452424:ios:259874b75d18916eae9bbd',
    messagingSenderId: '360003452424',
    projectId: 'interviewai-eb294',
    storageBucket: 'interviewai-eb294.firebasestorage.app',
    iosBundleId: 'com.interviewai.interviewai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGd2oysjiPd6r5no_TsWcrjxE7ZkVmk8M',
    appId: '1:360003452424:web:3a2c7054d5af46efae9bbd',
    messagingSenderId: '360003452424',
    projectId: 'interviewai-eb294',
    authDomain: 'interviewai-eb294.firebaseapp.com',
    storageBucket: 'interviewai-eb294.firebasestorage.app',
  );
}
